# values.yaml

image:
  repository: helm-demo-java-app
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  enabled: true
  annotations: {}
  type: ClusterIP
  port: 8080
  targetPort: 8080

ingress:
  enabled: true
  path: /
  annotations:
    kubernetes.io/ingress.class: "nginx"
