apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helm-demo
  template:
    metadata:
      labels:
        app: helm-demo
    spec:
      containers:
      - name: helm-demo
        image: 209479267348.dkr.ecr.us-east-1.amazonaws.com/helm-demo:latest # Replace with your Docker image
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: helm-demo
spec:
  type: LoadBalancer # Change to NodePort if needed
  selector:
    app: helm-demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
