apiVersion: v1
kind: Service
metadata:
  name: {? {include "helm-demo.fullname" .: ''} : ''}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: {? {include "helm-demo.name" .: ''} : ''}
    app.kubernetes.io/instance: {? {.Release.Name: ''} : ''}
